app_title: "Gem Notes"
db_host: "<aws-location>.pooler.supabase.com"
db_port: 5432
db_name: "postgres"
db_user: "gemnotes_app.<project-ref>"
table_name: "hours"
google_client_id: "<client-id>.apps.googleusercontent.com"
quotes:
  - "I love you.<br>- Dylan Pieper"
  - "You are loved.<br>- Dylan Pieper"
  - "Love yourself.<br>- Dylan Pieper"
